news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
]

newsportal/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('newsportalapp.urls')),
    path('business/', include('business.urls')),
    path('lifestyle/', include('lifestyle.urls')),
    path('sports/', include('sports.urls')),
    path('covid/', include('covid.urls')),
    path('entertainment/', include('entertainment.urls')),
    path('news/', include('news.urls')),
    path('tech/', include('tech.urls')),
    path('trending/', include('trending.urls')),

    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
        path('team/', views.Team.as_view(), name='team'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsportalapp/urls.py
from django.urls import path
from . import views

app_name = 'newsportalapp'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
    path('new-article/', views.NewsCreateView.as_view(), name='create_news'),
]

news/models.py
from django.db import models
from django.urls import reverse
from newsportalapp.utils import unique_slug_generator
from django.db.models.signals import pre_save


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Itself_News(models.Model):
    headline = models.CharField(max_length=255)
    reporter = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField()
    picture1 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    picture2 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    picture3 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    thumbnail = models.ImageField(upload_to=upload_location, blank=True, null=True)
    published_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)
    featured = models.BooleanField(default=False)
    event_place = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse("news:all", kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.id


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)


pre_save.connect(rl_pre_save_receiver, sender=Itself_News)

news/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Itself_News
from business.models import Business_News
from newsportalapp.models import News
from covid.models import Covid_News
from lifestyle.models import Lifestyle_News
from tech.models import Tech_News
from entertainment.models import Entertainment_News
from sports.models import Sports_News
from advertise.models import Advertising
from nepali_date import NepaliDate
import datetime

from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView


def all(request):
    business_news = Business_News.objects.order_by('-published_at')
    news_portal = News.objects.order_by('-published_at')
    news = Itself_News.objects.order_by('-published_at')
    covid_news = Covid_News.objects.order_by('-published_at')
    lifestyle_news = Lifestyle_News.objects.order_by('-published_at')
    tech_news = Tech_News.objects.order_by('-published_at')
    entertainment_news = Entertainment_News.objects.order_by('-published_at')
    sports_news = Sports_News.objects.order_by('-published_at')
    advertise = Advertising.objects.order_by('-timestamp')
    nep_date = NepaliDate.today()
    now = datetime.datetime.now()

    context = {'news': news, 'business_news': business_news, 'news_portal': news_portal, 'covid_news': covid_news, 'lifestyle_news':lifestyle_news, 'tech_news':tech_news, 'entertainment_news':entertainment_news, 'sports_news': sports_news, 'advertise': advertise, 'nep_date': nep_date, 'now':now}
    template = 'news/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        news = Itself_News.objects.get(slug=slug)
        advertise = Advertising.objects.order_by('-timestamp')
        nep_date = NepaliDate.today()
        now = datetime.datetime.now()

        all_news = Covid_News.objects.order_by('-published_at')[:4]

        context = {'news': news, 'advertise': advertise, 'all_news':all_news, 'nep_date': nep_date, 'now':now}
        template = 'news/single.html'
        return render(request, template, context)

    except:
        raise Http404


class NewsCreateView(CreateView):
    model = Itself_News
    fields = '__all__'

news/templates/news/all.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- samachar -->
{% include 'advertise/ad_home_top.html' %}

<section id="team">
    <div class="content-box-lg">
        <div class="container">
            <!-- Team Members-->
            <div class="alert alert-success" role="alert">
              <h2 class="alert-heading"> <a href="{% url 'news:all' %}">
                   समाचार
               </a></h2>
            </div>

            <div class="row">
                <!--- Team Right side-->
                <div class="col-md-12 col-sm-12 slideInRight" data-wow-duration="1s">
                    <div id="team-members" class="owl-carousel owl-theme">
                        <!-- Member 01-->
                        {% for np in news_portal %}

                        <div class="team-member">

                            <img src="{{ np.thumbnail.url }}" alt="team member" class="img-responsive" width="100%"
                                 height="250px">
                            <div class="team-member-overlay">
                                <div class="team-member-info text-center">
                                    <a href="{% url 'newsportalapp:single_news'  np.slug%}">
                                        <h6>{{np.headline|truncatechars:50}}</h6>
                                        <p>{{np.published_at|timesince}}</p>
                                    </a>
                                </div>
                            </div>
                        </div>

                        {% endfor %}


                    </div>
                </div>

            </div>


        </div>
    </div>
<br>
    <hr>


            <div class="col-sm-12 child-div">

                <div class="row row-cols-12 row-cols-md-4">
                    {% for n in news_portal|slice:"3:" %}
                    <a href="{% url 'newsportalapp:single_news' n.slug %}">
                        <div class="col mb-12">
                            <div class="card">
                                <img src="{{n.thumbnail.url}}" class="card-img-top" alt="..." width="200px" height="200px">
                                <div class="card-body">
                                    <h5 class="card-title">{{n.headline|truncatechars:35}}</h5>
                                </div>
                            </div>
                        </div>
                    </a>

                    {% endfor %}

                </div>
            </div>
</section>
</div>

 {% include 'advertise/ad_home_bottom.html' %}

{% endblock %}

news/templates/news/single.html
{% extends 'base.html' %}

<meta property="og:url"                content="http://shuvapravatkhabar.com/{{news.slug}}"/>
{% block content %}
{% include 'singlead/singletop.html' %}

<section id="single">
    <div class="container-fluid single">
        <h1 >{{news.headline}}</h1>
        <div class="row">
            {% if news.reporter %}
            <div class="col-md-3">
                <p><i class="fa fa-pencil" aria-hidden="true"></i><span >{{news.reporter}}</span></p></div>
            {% endif %}
            {% if news.published_at %}
            <div class="col-md-6">
                <i class="fa fa-calendar"></i><span>{{news.published_at}}</span></i>
            </div>
            {% endif %}
            {% if news.event_place %}
        <div class="col-md-3">
                <i class="fa fa-map-marker"></i><span>{{news.published_at}}</span></i>
            </div>
            {% endif %}
        </div>

        <img src="{{ news.thumbnail.url }}" width="100%" height="600px">
        <div class="jumbotron">
                       <dl>
                <p>    {{news.description|safe|linebreaksbr}}</p>

  <!-- Other terms and descriptions -->
</dl>
        {%if news.picture1 %}
            <img src="{{ news.picture1.url }}" width="100%" height="300px" class="img-responsive">
            <br>
            <br>
        {% endif %}
        {%if news.picture2 %}
            <img src="{{ news.picture2.url }}" width="100%" height="300px" class="img-responsive">
        <br><br>
            {% endif %}
        {%if news.picture3 %}
            <img src="{{ news.picture3.url }}" width="100%" height="300px" class="img-responsive">
        {% endif %}

        </div>
    </div>
               <div class="col-md-3">
            {% include 'singlead/singleright.html' %}
        </div>
    </div>
    {% include 'singlead/singlebottom.html' %}

</section>
            <div class="row">
                {% for t in all_news %}
                <div class="col-sm-3">
                    <div class="card-deck">
                        <div class="card">
                            {% if t.thumbnail %}
                            <a href="{% url 'news:single_news' t.slug %}">
                                <img src="{{t.thumbnail.url}}" class="card-img-top" alt="...">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                                         <a href="{% url 'news:single_news' t.slug %}">

                                <h5 class="card-title">{{t.headline}}</h5>
                                                         </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

{% endblock %}