news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
]

newsportal/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('newsportalapp.urls')),
    path('business/', include('business.urls')),
    path('lifestyle/', include('lifestyle.urls')),
    path('sports/', include('sports.urls')),
    path('covid/', include('covid.urls')),
    path('entertainment/', include('entertainment.urls')),
    path('news/', include('news.urls')),
    path('tech/', include('tech.urls')),
    path('trending/', include('trending.urls')),

    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
        path('team/', views.Team.as_view(), name='team'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trending/urls.py
from django.urls import path
from . import views

app_name = 'trending'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
]

trending/models.py
from django.db import models
from django.urls import reverse
from newsportalapp.utils import unique_slug_generator
from django.db.models.signals import pre_save


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Trending_News(models.Model):
    headline = models.CharField(max_length=255)
    reporter = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField()
    picture1 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    picture2 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    picture3 = models.ImageField(upload_to=upload_location, blank=True, null=True)
    thumbnail = models.ImageField(upload_to=upload_location, blank=True, null=True)
    published_at = models.DateTimeField(auto_now_add=True)
    event_place = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse("trending:all", kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.id


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
        if not instance.slug:
            instance.slug = unique_slug_generator(instance)


pre_save.connect(rl_pre_save_receiver, sender=Trending_News)

trending/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Trending_News
from advertise.models import Advertising
from nepali_date import NepaliDate
import datetime


def all(request):
    trending = Trending_News.objects.order_by('-published_at')
    advertise = Advertising.objects.order_by('-timestamp')
    nep_date = NepaliDate.today()
    now = datetime.datetime.now()

    context = {'trending': trending, 'advertise': advertise, 'nep_date': nep_date, 'now':now}
    template = 'trending/all.html'
    return render(request, template, context)


def single(request, slug):
    try:
        advertise = Advertising.objects.order_by('-timestamp')
        news = Trending_News.objects.get(slug=slug)
        nep_date = NepaliDate.today()
        now = datetime.datetime.now()

        all_news = Trending_News.objects.order_by('-published_at')[:4]

        context = {'news': news, 'advertise': advertise, 'all_news': all_news, 'nep_date': nep_date, 'now':now}
        template = 'trending/single.html'
        return render(request, template, context)

    except:
        raise Http404

trending/templates/trending/all.html
{% extends 'base.html' %}

{% block content %}
{% include 'advertise/ad_home_top.html' %}

<div class="col-md-9">

    <section>
        <div class="container">
            <hr>

            <div class="col-sm-12 child-div">

                <div class="row row-cols-12 row-cols-md-4">
                    {% for t in trending %}
                    <a href="{% url 'trending:single_news' t.slug %}">
                        <div class="col mb-12">
                            <div class="card">

                                <img src="{{t.thumbnail.url}}" class="card-img-top" alt="..." width="200px"
                                     height="200px">
                                <div class="card-body">
                                   hi <h5 class="card-title">{{t.headline|truncatechars:35}}</h5>
                                </div>
                            </div>
                        </div>
                    </a>

                    {% endfor %}

                </div>
            </div>


        </div>
    </section>

    <hr>
</div>

            {% include 'advertise/ad_home_bottom.html' %}

<br><br><br>
<br><br><br>
<hr>
{% endblock %}