business/urls.py
from django.urls import path
from . import views

app_name = 'business'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
]

covid/urls.py
from django.urls import path
from . import views

app_name = 'covid'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
    path('new-article/', views.NewsCreateView.as_view(), name='create_news'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
]

newsportal/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('newsportalapp.urls')),
    path('business/', include('business.urls')),
    path('lifestyle/', include('lifestyle.urls')),
    path('sports/', include('sports.urls')),
    path('covid/', include('covid.urls')),
    path('entertainment/', include('entertainment.urls')),
    path('news/', include('news.urls')),
    path('tech/', include('tech.urls')),
    path('trending/', include('trending.urls')),

    path('advertising/', include('advertise.urls'), name='advertising'),

    path('s/', views.search, name='search'),
        path('team/', views.Team.as_view(), name='team'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views

app_name = 'sports'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
    path('new-article/', views.NewsCreateView.as_view(), name='create_news'),
]

tech/urls.py
from django.urls import path
from . import views

app_name = 'tech'

urlpatterns = [
    path('', views.all, name='all'),
    path('<slug>', views.single, name='single_news'),
    path('new-article/', views.NewsCreateView.as_view(), name='create_news'),
]

templates/snippets/css.html
{% load static %}


<!--    Google fonts-->
<link href="https://fonts.googleapis.com/css2?family=Karma:wght@400;600;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Hind:wght@600&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Mukta:wght@500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Halant:wght@300;400;500&display=swap" rel="stylesheet">

<!--font awesome-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css">


<link rel="stylesheet" href="{% static 'css/master5.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

templates/snippets/footer.html
 <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <p>
                        <a href="{% url 'advertise:advertiseinfo' %}"> click here to contact for <span>Advertising</span></a>
                    </p>
                </div>
                <div class="col-md-8">
                    <p>
                        Copyright &copy; 2020 All Rights Reserverds By <span>ShuvaPravat Khabar</span>
                    </p>
                </div>

            </div>
        </div>
        <!-- Back To Top -->
       <a href="#home" id="back-to-top" class="btn btn-sm btn-yellow btn-back-to-top smooth-scroll hidden-sm hidden-xs" title="home" role="button">
        <i class="fa fa-angle-up"></i>
       </a>
    </footer>
    <!--Footer Ends-->

templates/snippets/footer_stack.html
{% load static %}
<!-- Contact -->
<section id="footer-stack">
    <div class="content-box-md">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div id="contact-left">
                        <div class="vertical-heading">
                            <h2><strong> शुभप्रभात खबर</strong></h2>
                        </div>
                        <div id="offices">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="office">
                                        <ul class="office-details">
                                            <!--<li><img src="{% static 'images/tarun.jpg' %}" width="100px" height="80px"></li>-->
                                            <li><i class="fa fa-pencil-square-o" aria-hidden="true"></i> <span>प्रधान सम्पादक : तरुण भारती </span></li>
                                            <li><i class="fa fa-mobile"></i> <span>+(977) 9852660180</span></li>
                                            <li><i class="fa fa-envelope"></i><span> news@shuvapravatkhabar.com</span>
                                            </li>

                                            <li><i class="fa fa-map-marker"></i><span> Phungling Bazzar, <br>
                                                        Taplejung, Nepal</span></li>

                                        </ul>
                                    </div>

                                </div>
                                 <div class="col-md-6">
                                  

                                </div>
                                <ul class="social-list">
                                    <li><a href="https://www.facebook.com/shuvapravatkhabar/"><i
                                            class="fa fa-facebook"></i></a></li>
                                    <li><a href="https://twitter.com/shuvapravat"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="https://www.youtube.com/channel/UCN0Esg_c7w-jVXIbe7SXwRQ"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-md-2">
                    <div id="contact-left">
                        <div class="vertical-heading">
                            <a href="{% url 'entertainment:all' %}"><h3>मनोरञ्जन </h3></a>
                        </div>
                        <div id="offices">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="office">
                                        <a href="{% url 'entertainment:all' %}">
                                        <ul class="office-details">
                                            <a href="{% url 'newsportalapp:all'%}" ><li><span>ताजा समाचार</span></li></a>
                                            <br>
                                            <li><span>गसिप</span></li>
                                            <br>
                                            <li><span>बलिउड / हलिउड</span></li>
                                            <br>
                                            <a href="https://www.youtube.com/channel/UCN0Esg_c7w-jVXIbe7SXwRQ"><li><span>भिडियो</span></li></a>
                                            <br>
                                            <a href="{% url 'team'%}" ><li><span>सम्पादक </span></li></a>

                                        </ul>
                                            </a>
                                    </div>

                                </div>

                            </div>
                        </div>


                    </div>
                </div>

                <div class="col-md-2">
                    <div id="contact-left">
                        <div class="vertical-heading">
                            <a href="{% url 'news:all' %}"><h3>समाचार </h3></a>
                        </div>
                        <div id="offices">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="office">
                                       <a href="{% url 'news:all' %}">
                                        <ul class="office-details">
                                            <li><span>समाज</span></li>
                                            <br>
                                            <li><span>जीवनशैली/स्वास्थ</span></li>
                                            <br>
                                            <li><span>प्रवास</span></li>
                                            <br>
                                            <li><span>अन्तराष्ट्रिय</span></li>
                                            <br>
                                            <a href="{% url 'sports:all'%}" ><li><span>खेलकुद़़</span></li></a>
                                            <br>
                                        </ul>
                                       </a>
                                    </div>

                                </div>

                            </div>
                        </div>


                    </div>
                </div>

                <div class="col-md-2">
                    <div id="contact-left">
                        <div class="vertical-heading">
                            <a href="{% url 'business:all' %}"><h3>विजनेश </h3></a>
                        </div>
                        <div id="offices">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="office">
                            <a href="{% url 'business:all' %}">

                                        <ul class="office-details">
                                            <li><span>पर्यटन</span></li>
                                            <br>
                                            <li><span>अटो</span></li>
                                            <br>
                                            <li><span>बैँक / वित्त</span></li>
                                            <br>
                                            <a href="{% url 'tech:all'%}" > <li><span>सूचना-प्रविधि</span></li></a>
                                            <br>

                                        </ul>
                            </a>
                                    </div>

                                </div>

                            </div>
                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>
</section>
<!-- footer stack Ends-->

templates/snippets/header.html
<!--{% load static %}-->
<!--{% load nepalidatetime %}-->
<!--<div class="header">-->
<!--        <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-">-->
<!--                <img src="{% static 'images/spk_icon.jpg' %}" class="img-responsive">-->
<!--            </div>-->
<!--            <div class="col-">-->
<!--                <h3>{% nepalinow %}</h3>-->
<!--                <h3>{{now|time}}</h3>-->
<!--            </div>-->
<!--        </div>-->
<!--        </div>-->
<!--</div>-->

{% load static %}
{% load nepalidatetime %}
<div class="header">

<div class="container">
  <div class="row">
    <div class="col fill">
                        <img src="{% static 'images/spk_icon.jpg' %}" class="img-responsive">

    </div>
    <div class="col">
     <h3>{% nepalinow %}</h3>
                <h3>{{now|time}}</h3>
    </div>
  </div>
</div>
</div>

templates/snippets/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>

<script src="{% static 'js/master.js' %}"></script>

templates/snippets/meta.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-compatible" content="IE-edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta property="og:type"               content="article"/>
<meta property="og:title"              content="{{news.headline}}"/>
<meta property="og:description"        content="{{news.description}}"/>
<meta property="og:image:url"              content="http://shuvapravatkhabar.com{{news.thumbnail.url}}"/>
<meta property="og:image"              content="http://shuvapravatkhabar.com{{news.thumbnail.url}}"/>
<meta property="og:image:width"              content="1080px"/>
<meta property="og:image:height"              content="720px"/>

templates/snippets/nav.html
{% load static %}



 <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #006d77;">
 <a class="navbar-brand" href="{% url 'newsportalapp:all' %}"><i class="fas fa-home"></i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
             
            <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'newsportalapp:all' %}"> होमपेज</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'news:all' %}">समाचार</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'business:all' %}">विजनेश</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'lifestyle:all' %}">जीवनशैली</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'tech:all' %}">सूचना प्रविधि</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'entertainment:all' %}">मनोरन्जन</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'trending:all' %}">ट्रेंडिंग</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'sports:all' %}">खेलकुद</a>
              </li>
              <li class="nav-item pr-2">
                <a class="nav-link" href="{% url 'covid:all' %}">कोरोना भाइरस</a>
              </li>
        </ul>
          <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.facebook.com/shuvapravatkhabar/"><i
                                            class="fa fa-facebook"></i> </a>
              </li><li class="nav-item">
                <a class="nav-link" href="https://twitter.com/shuvapravat"><i class="fa fa-twitter"></i> </a>
              </li><li class="nav-item">
                <a class="nav-link" href="https://www.youtube.com/channel/UCN0Esg_c7w-jVXIbe7SXwRQ"><i class="fa fa-youtube-play" aria-hidden="true"></i> </a>
              </li>
          </ul>
      </div>

  </nav>

templates/snippets/responsive.html
/*mobile menu*/
#mobile-nav-open-btn{
    font-size: 30px;
    color: #f4c613;
    cursor: pointer;
    z-index: 2;
    right: 0;
    top: 6px;
    /*hide mobile nav open btn*/
    display: none;
}
#mobile-nav{
	/* by default movie nav will be hidden with height 0%*/
    height: 0%;
    width: 100%;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 3;
    background-color: rgba(255,255,255,.9);
    -webkit-transition:all 300ms linear;
    transition: all 300ms linear;
    overflow-y: hidden;
}
#mobile-nav-close-btn{
    font-family: "Raleway",sans-serif;
    font-size: 70px;
    color: #212226;
    font-weight: 400;
    cursor: pointer;
    position: absolute;
    top: -9px;
    right: 13px;
    -webkit-transition:.3s;
    transition: .3s;
}

#mobile-nav-content{
    text-align: center;
    width: 100%;
    margin-top: 30px;
    position: relative;
    top: 10%;
}
#mobile-nav ul li{
    margin-bottom: 20px;
}
#mobile-nav a{
    font-family: "Raleway",sans-serif;
    font-size: 18px;
    color: #212226;
    font-weight: 400;
    text-transform: uppercase;
    display: inline;
  -webkit-transition:.3s;
    transition: .3s;
}
#mobile-nav a:hover,
#mobile-nav a:focus,
#mobile-nav-close-btn:hover,
#mobile-nav-close-btn:focus{
    color: #f4c613;
    background: none;
}

/*mobile nav Scroll spy active state*/
.white-nav-top #mobile-nav ul.nav>li.active>a{
    color: #f4c613;
    font-weight: 500;
}

/*bootstrap 3 media queries */
/* Large devices(desktops and laptops)*/
@media(min-width: 1200px) and (max-width: 1299px){
	/* Large devices*/
	.site-nav-wrapper{
		padding: 0 20px;
	}
}
/*Medium devices(landscape tablets and medium desktops*/
@media(min-width: 992px) and (max-width: 1199px){
	/*navigation */
	.site-nav-wrapper{
		padding: 0;
	}
	/* Generic */
	.vertical-heading h2{
		font-size: 29px;
	}
	/*Services 02*/
	#services-tabs .tab-bg{
		padding: 16px 30px;
		min-height: 300px;
	}
	.service-tab p{
		line-height: 20px;
	}
}
/*Small devices(portrait tablets and small desktops*/
@media(min-width: 768px) and (max-width: 991px){
	/*Navigation*/
	.site-nav-wrapper{
		padding: 0;
	}
	/*home*/
	#home-heading h1{
		font-size: 41px;
	}
	#home-text p{
		font-size: 13px;
	}

	.btn-general{
		padding: 8px 35px 8px 35px;
		font-size: 10px;
	}
	/*Generic*/
	.vertical-heading h2{
		font-size: 29px;
	}
	/*Tech statement*/
	#tech-statement h3{
		font-size: 20px;
		line-height: 30px;
	}
	/*Services 02*/
	.r-tabs-accordion-title{
		text-align: center;
		margin-bottom: 10px;
	}
	.r-tabs-accordion-title a{
   	   font-family: "Raleway", sans-serif;
	    font-size: 13px;
	    color: #212226;
	    text-transform: uppercase;
	    font-weight: 400;
	    padding: 0;
	    text-decoration: none;
	}
	/*  Tabs active status*/
	.r-tabs-accordion-title.r-tabs-state-active a {
    color: #f4c613;
    font-weight: 700;
    border-bottom: 3px solid #f4c613;
    padding-bottom: 5px;
    transition: border-color 300ms linear;
}
/*Pricing*/
.pricing-table .price h2{
	margin: 0 0 0 6px;
	font-size: 35px;
	}
	/*stats*/
	.stats-item p{
		line-height: 18px;
	}
	/*BLOG*/
	.blog-post .post-meta p{
		line-height: 14px;
	}
	/*Contact*/
	ul.office-details li{
		margin-right: 15px;
	}
	ul.office-details li i{
		width: 25px;
	}
}

/*Extra Small devices(Landscape Phone and portrait tablets*/
@media(max-width: 767px){
	/*Navigation*/
	.navbar{
		padding: 20px 0;
	}
	.site-nav-wrapper,
	.white-nav-top{
		padding: 0;
	}
	/*show mobile menu open btn*/
	#mobile-nav-open-btn{
		display: block;
	}

	/*home*/
	#home-heading h1{
		font-size: 22px;
	}
	#home-text p{
		font-size: 13px;
		line-height: 18px;
		margin: 8px 2px 30px 2px;
	}
	.btn-general{
		padding: 8px 25px 6px 25px;
		font-size: 10px;
	}
		/*About 01*/
		/*Large content box*/
		.content-box-lg{
			padding: 90px 0;
		}

		/*Vertical heading*/
		.vertical-heading{
			text-align: center;
		}
		.vertical-heading h5{
			-webkit-transform:rotate(0deg);
			transform: rotate(0deg);
			display: block;
			position: static;
			margin-bottom: 15px;
		}
		.vertical-heading h2{
			font-size: 29px;
			line-height: normal;
			margin: 0;
		}
		#about-left{
			margin-bottom: 50px;
		}
		#about-right{
			text-align: center;
		}
		/*about 02*/
		/*medium content box*/
		.content-box-md{
			padding: 80px 0;
		}
		.about-item{
			padding: 55px 30px;
			margin-bottom: 35px;
		}
		.about-item i{
			font-size: 30px;
		}
		.about-item h3{
			font-size: 18px;
		}
		#team-left .vertical-heading{
			min-height: 130px;
		}
		.skill h4{
			font-size: 14px;
			line-height: 35px;
		}
		/*tech statement*/
		#tech-statement h3{
			font-size: 20px;
			line-height: 30px;
		}
		/*services 01*/
		/*horizontal heading*/
		.horizontal-heading{
			margin-bottom: 40px;
		}
		.horizontal-heading h2{
			font-size: 30px;
		}
		#services-01 img{
			margin: 35px 0;
		}
		.service, .service .icon{
			text-align: center;
		}
		.service h4{
			font-size: 18px;
		}

	/*Services 02*/
	.r-tabs-accordion-title{
		text-align: center;
		margin-bottom: 10px;
	}
	.r-tabs-accordion-title a{
   	   font-family: "Raleway", sans-serif;
	    font-size: 13px;
	    color: #212226;
	    text-transform: uppercase;
	    font-weight: 400;
	    padding: 0;
	    text-decoration: none;
	}
	/*  Tabs active status*/
	.r-tabs-accordion-title.r-tabs-state-active a {
    color: #f4c613;
    font-weight: 700;
    border-bottom: 3px solid #f4c613;
    padding-bottom: 5px;
    transition: border-color 300ms linear;
}
	#services-tabs .tab-bg{
		text-align: center;
		padding: 40px 30px;
	}
	#services-tabs h2{
		font-size: 40px;
	}
	#services-tabs h3{
		font-size: 28px;
	}
	/*PORTFOLIO*/
	#portfolio{
		padding-bottom: 0;
	}
	#isotope-filters button{
		padding-right: 15px;
	}
	/*testiomonial*/
	#testimonials{
		padding-top: 45px;
	}
	#testimonial-slider{
		top: 0;
	}
	#testimonials .vertical-heading{
		padding: 0;
	}
	.testimonial .row{
		margin: 0;
	}
	.testimonial h3{
		font-size: 20px;
	}
	.testimonial .stars{
		font-size: 16px;
	}
.author img{
	width: 80px !important;
}
	/*pricing*/
.pricing-table{
	margin-bottom: 30px;
}
.pricing-table .price h2{
	font-size: 28px;
	margin: 0 0 0 16px;
}
/*stats*/
.stats-item{
	margin-bottom: 20px;
	padding: 25px 5px;
}
.stats-item{
	font-size: 30px;
}
.stats-item h3{
	font-size: 24px;
}
/*blog*/
#blog-left{
	text-align: center;
	margin-bottom: 30px;
}
.blog-post{
	margin-bottom: 25px;
}
/* contact*/
#contact-left {
	text-align: center;
}
.office{
	margin-bottom: 40px;
}
ul.office-details li{
	display: block;
	margin-top: 25px;
}
ul.office-details li i{
	width: auto;
	display: block;
	margin-bottom: 3px;
}
ul.social-list{
	margin-bottom: 40px;
}

/*EXTRA STAMM */
@media(max-width: 480px){
	/*home*/
	#home-heading h1{
		font-size: 18px;
	}
	#home-text p{
		font-size: 11px;
		line-height: 16px;
		margin: 8px 10px 25px 10px;
	}
	/*Generic*/
	.vertical-heading h2{
		font-size: 22px;
	}
/*portfolio*/
	#isotope-filters{
		text-align: center;
	}
	#isotope-filters button{
		font-size: 10px;
		padding-right: 14px;
	}
	/*testimonials */
	.testimonial h3{
		font-size: 14px;
		line-height: 18px;
	}
	.testimonial .stars{
		font-size: 13px;
	}
}
/*extra small devices*/
@media(max-width: 320px){
	/*testimonials */
	.testimonial h3{
		font-size: 12px;
		line-height: 16px;
	}
	.testimonial .stars{
		font-size: 10px;
	}
}















}